#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-osgi-resource-locator
Version  : 1.0.1
Release  : 1
URL      : https://repo1.maven.org/maven2/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar
Source0  : https://repo1.maven.org/maven2/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar
Source1  : https://repo1.maven.org/maven2/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CDDL-1.0 GPL-2.0
Requires: mvn-osgi-resource-locator-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-osgi-resource-locator package.
Group: Data

%description data
data components for the mvn-osgi-resource-locator package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar
/usr/share/java/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.pom
